up:
	COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose -f ./docker/docker-compose.yml up -d --build --remove-orphans

down:
	docker compose -f ./docker/docker-compose.yml down

stop:
	docker compose -f ./docker/docker-compose.yml stop

